pipeline {
    agent {
        docker {
            image 'golang:1.20'
        }
    }

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}